/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import model.Produto;
import Controller.ControladorProduto;
import java.math.BigDecimal;
import javax.swing.JOptionPane;
/**
 *
 * @author Joao Maggi
 */
public class TelaCadastrarProduto extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastarProduto
     */
    public TelaCadastrarProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        textClienteNome = new javax.swing.JTextField();
        textClienteEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textClienteCpf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textCodigoProduto = new javax.swing.JTextField();
        textNomeProduto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textPreçoProduto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textDescricaoProduto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnCadastrarProduto = new javax.swing.JButton();

        jLabel3.setText("NOME:");

        textClienteEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textClienteEmailActionPerformed(evt);
            }
        });

        jLabel4.setText("EMAIL:");

        jLabel5.setText("CPF:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("SERVE UP");

        jLabel2.setText("CADASTRO PRODUTO");

        jLabel6.setText("CODIGO:");

        textCodigoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCodigoProdutoActionPerformed(evt);
            }
        });

        textNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomeProdutoActionPerformed(evt);
            }
        });

        jLabel7.setText("NOME:");

        jLabel8.setText("PREÇO:");

        jLabel9.setText("DESCRIÇÃO:");

        btnVoltar.setText("VOLTAR");

        btnCadastrarProduto.setText("CADASTRAR");
        btnCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1))
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(textCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textPreçoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel6))))
                .addContainerGap(108, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadastrarProduto)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(13, 13, 13)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(textPreçoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(textDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnCadastrarProduto))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textClienteEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textClienteEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textClienteEmailActionPerformed

    private void textNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomeProdutoActionPerformed

    private void textCodigoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCodigoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCodigoProdutoActionPerformed

    private void btnCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarProdutoActionPerformed
        cadastraProdutos();
    }//GEN-LAST:event_btnCadastrarProdutoActionPerformed

   public void cadastraProdutos(){

    try {
        // --- 1. Coleta dos dados da tela como Texto ---
        String codigoString = textCodigoProduto.getText();
        String nome = textNomeProduto.getText();
        String descricao = textDescricaoProduto.getText();
        String precoString = textPreçoProduto.getText();

        // --- 2. Validação de campos obrigatórios ---
        if (codigoString.trim().isEmpty() || nome.trim().isEmpty() || precoString.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Código, Nome e Preço são obrigatórios!", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
            return; // Interrompe a execução
        }

        // --- 3. Conversão de Tipos e Validação de Formato ---
        // Se o preço não for um número válido, a linha abaixo vai lançar uma NumberFormatException
        BigDecimal preco = new BigDecimal(precoString.replace(",", ".")); // Troca vírgula por ponto
        int codigo = Integer.parseInt(codigoString);
        // Validação extra: o preço não pode ser negativo
        if (preco.compareTo(BigDecimal.ZERO) < 0) {
            JOptionPane.showMessageDialog(this, "O preço não pode ser um valor negativo.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
            return;
        }else if (codigo < 0){
            JOptionPane.showMessageDialog(this, "O codigo nao pode ser Nulo", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
        }

        // --- 4. Cria o objeto Produto (APENAS se todas as validações passaram) ---
        Produto produto = new Produto();
        produto.setCodigoProduto(codigo);
        produto.setNome(nome);
        produto.setDescricao(descricao);
        produto.setPreco(preco);

        // --- 5. Chama o controlador para salvar ---
        ControladorProduto cont = new ControladorProduto();
        cont.inserir(produto);

        // --- 6. Feedback de sucesso e limpeza da tela ---
        JOptionPane.showMessageDialog(this, "Produto cadastrado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

        textCodigoProduto.setText("");
        textNomeProduto.setText("");
        textDescricaoProduto.setText("");
        textPreçoProduto.setText("");

        } catch (NumberFormatException e) {
            // Este 'catch' é específico para erros de conversão de número
            JOptionPane.showMessageDialog(this, "Erro de Formato: O preço deve ser um número válido (ex: 10.50).", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
        } catch (RuntimeException e) {
            // Este 'catch' captura outros erros, como os do banco de dados (ex: código duplicado)
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar produto:\n" + e.getMessage(), "Erro no Banco de Dados", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarProduto;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField textClienteCpf;
    private javax.swing.JTextField textClienteEmail;
    private javax.swing.JTextField textClienteNome;
    private javax.swing.JTextField textCodigoProduto;
    private javax.swing.JTextField textDescricaoProduto;
    private javax.swing.JTextField textNomeProduto;
    private javax.swing.JTextField textPreçoProduto;
    // End of variables declaration//GEN-END:variables
}
